CREATE DATABASE IF NOT EXISTS notesdb;
USE notesdb;

CREATE TABLE IF NOT EXISTS User (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS AuthUser (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

-- Beispiel-User anlegen

CREATE TABLE IF NOT EXISTS Note (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255),
  content TEXT,
  ownerId INT,
  lastEditorId INT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ownerId) REFERENCES User(id),
  FOREIGN KEY (lastEditorId) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS Collaborator (
  id INT AUTO_INCREMENT PRIMARY KEY,
  noteId INT,
  userId INT,
  role VARCHAR(50),
  FOREIGN KEY (noteId) REFERENCES Note(id),
  FOREIGN KEY (userId) REFERENCES User(id)
);
